apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: sample-app-config
  namespace: roofstacks-sample
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    port: 80
    requestPath: /WeatherForecast